<a href="https://colab.research.google.com/github/Neel7317/PyTorch/blob/main/Pytorch_(1_tensor).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

Initializing a Tensor

In [3]:
#Directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
#from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
#From another tensor:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2656, 0.6210],
        [0.5247, 0.2526]]) 



In [7]:
#With random or constant values:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1462, 0.3059, 0.4249],
        [0.5612, 0.6994, 0.5548]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# Attributes of a Tensor
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [4]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [5]:
tensor.device

device(type='cuda', index=0)

In [6]:
#some of the operations
tensor

tensor([[0.3931, 0.5333, 0.0749, 0.2593],
        [0.7108, 0.9834, 0.9310, 0.2426],
        [0.3451, 0.7717, 0.7026, 0.3308]], device='cuda:0')

In [9]:
tensor[0] # first raw

tensor([0.3931, 0.5333, 0.0749, 0.2593], device='cuda:0')

In [10]:
tensor[:,0] # first column

tensor([0.3931, 0.7108, 0.3451], device='cuda:0')

In [11]:
tensor[:,-1] # last column

tensor([0.2593, 0.2426, 0.3308], device='cuda:0')

In [13]:
tensor[:,1]=0 # change the value of tensor column
tensor

tensor([[0.3931, 0.0000, 0.0749, 0.2593],
        [0.7108, 0.0000, 0.9310, 0.2426],
        [0.3451, 0.0000, 0.7026, 0.3308]], device='cuda:0')

In [14]:
tensor[0,0] # indexing

tensor(0.3931, device='cuda:0')

Joining tensors

In [16]:
tensor2=torch.ones(3,4)
tensor2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
tensor2.device

device(type='cpu')

In [18]:
tensor2=tensor2.to("cuda")
tensor2.device

device(type='cuda', index=0)

In [19]:
tensor2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [22]:
joined_tensor=torch.cat([tensor,tensor2],dim=1) # horizontally concate
joined_tensor

tensor([[0.3931, 0.0000, 0.0749, 0.2593, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.7108, 0.0000, 0.9310, 0.2426, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.3451, 0.0000, 0.7026, 0.3308, 1.0000, 1.0000, 1.0000, 1.0000]],
       device='cuda:0')

In [23]:
joined_tensor2=torch.cat([tensor,tensor2],dim=0) # vertically concate
joined_tensor2

tensor([[0.3931, 0.0000, 0.0749, 0.2593],
        [0.7108, 0.0000, 0.9310, 0.2426],
        [0.3451, 0.0000, 0.7026, 0.3308],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]], device='cuda:0')

Arithmetic operations

In [24]:
tensor.T #matrix transformation

tensor([[0.3931, 0.7108, 0.3451],
        [0.0000, 0.0000, 0.0000],
        [0.0749, 0.9310, 0.7026],
        [0.2593, 0.2426, 0.3308]], device='cuda:0')

In [25]:
y2 = tensor.matmul(tensor.T) #multiplication
y2

tensor([[0.2274, 0.4120, 0.2740],
        [0.4120, 1.4307, 0.9796],
        [0.2740, 0.9796, 0.7222]], device='cuda:0')

In [29]:
z2 = tensor.mul(tensor.T) #element wise multiplication need same shape
z2

RuntimeError: ignored

In [30]:
z2 = tensor.mul(tensor) #element wise multiplication need same shape
z2

tensor([[0.1545, 0.0000, 0.0056, 0.0673],
        [0.5052, 0.0000, 0.8667, 0.0588],
        [0.1191, 0.0000, 0.4937, 0.1094]], device='cuda:0')