<a href="https://colab.research.google.com/github/Neel7317/PyTorch/blob/main/Transform(PyTorch_3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

transform to modify the features and target_transform to modify the labels -

In [1]:
import torch
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
)

100%|██████████| 26421880/26421880 [00:01<00:00, 16893433.53it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 276460.54it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:00<00:00, 4985769.29it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 17163972.17it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device


In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [4]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [5]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7], device='cuda:0')


In [8]:
input_image = torch.rand(3,28,28)
print(input_image)
print(input_image.size())

tensor([[[0.7755, 0.0329, 0.5335,  ..., 0.0769, 0.9422, 0.8666],
         [0.9808, 0.8221, 0.3223,  ..., 0.2991, 0.9761, 0.7161],
         [0.4995, 0.4432, 0.8477,  ..., 0.8462, 0.2418, 0.7333],
         ...,
         [0.9485, 0.2312, 0.9520,  ..., 0.4849, 0.5254, 0.4951],
         [0.0803, 0.5611, 0.0733,  ..., 0.4580, 0.8650, 0.3394],
         [0.4436, 0.9739, 0.9464,  ..., 0.5682, 0.1848, 0.9067]],

        [[0.7492, 0.5759, 0.1479,  ..., 0.5884, 0.7269, 0.9061],
         [0.4289, 0.1016, 0.3639,  ..., 0.1530, 0.8246, 0.8911],
         [0.4163, 0.8945, 0.6895,  ..., 0.8692, 0.5482, 0.2786],
         ...,
         [0.5010, 0.3113, 0.4639,  ..., 0.0601, 0.1985, 0.8467],
         [0.7869, 0.9931, 0.9065,  ..., 0.7074, 0.8866, 0.4269],
         [0.7097, 0.5391, 0.2803,  ..., 0.4883, 0.6359, 0.4479]],

        [[0.4202, 0.7190, 0.6890,  ..., 0.3657, 0.0871, 0.0135],
         [0.5289, 0.8727, 0.1960,  ..., 0.5065, 0.7800, 0.6607],
         [0.7308, 0.7237, 0.6003,  ..., 0.6816, 0.8212, 0.

In [10]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image)
print(flat_image.size())

tensor([[0.7755, 0.0329, 0.5335,  ..., 0.5682, 0.1848, 0.9067],
        [0.7492, 0.5759, 0.1479,  ..., 0.4883, 0.6359, 0.4479],
        [0.4202, 0.7190, 0.6890,  ..., 0.9508, 0.6777, 0.7206]])
torch.Size([3, 784])


In [11]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [12]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.2716,  0.0499,  0.3139,  0.4919, -0.0476,  0.2370,  0.1283, -0.5312,
          0.1271,  0.3398, -0.3658,  0.0282,  0.4373,  0.3379,  0.6873, -0.4310,
          0.0361, -0.6010,  0.1019,  0.2021],
        [-0.1865,  0.0333,  0.3463, -0.2758, -0.0879,  0.1923, -0.0486, -0.3140,
          0.1517,  0.4299, -0.3775,  0.1017,  0.2466,  0.2851,  0.6608, -0.2293,
          0.1972, -0.5931,  0.2928,  0.0093],
        [-0.0086, -0.0937,  0.1554,  0.2851,  0.0841,  0.3313,  0.1429, -0.3023,
         -0.1976,  0.6180, -0.3774,  0.1352,  0.1288,  0.4926,  0.6011, -0.1258,
         -0.1279, -0.7310,  0.0912,  0.3801]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.0499, 0.3139, 0.4919, 0.0000, 0.2370, 0.1283, 0.0000, 0.1271,
         0.3398, 0.0000, 0.0282, 0.4373, 0.3379, 0.6873, 0.0000, 0.0361, 0.0000,
         0.1019, 0.2021],
        [0.0000, 0.0333, 0.3463, 0.0000, 0.0000, 0.1923, 0.0000, 0.0000, 0.1517,
         0.4299, 0.0000, 0.1017, 0.2466, 0.2851, 0.66

In [13]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)
logits

tensor([[ 0.1966, -0.0915,  0.1515, -0.0347,  0.3804, -0.3393, -0.0921, -0.2999,
          0.0544,  0.2200],
        [ 0.2531, -0.1665,  0.2256, -0.0494,  0.2420, -0.2932, -0.0498, -0.3038,
          0.1621,  0.0427],
        [ 0.1743, -0.2053,  0.1046,  0.0352,  0.3382, -0.3893, -0.1477, -0.4862,
          0.2631,  0.1402]], grad_fn=<AddmmBackward0>)

In [15]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
pred_probab

tensor([[0.1172, 0.0878, 0.1120, 0.0930, 0.1408, 0.0686, 0.0878, 0.0713, 0.1016,
         0.1199],
        [0.1254, 0.0825, 0.1220, 0.0927, 0.1240, 0.0726, 0.0927, 0.0719, 0.1145,
         0.1016],
        [0.1172, 0.0802, 0.1093, 0.1020, 0.1380, 0.0667, 0.0849, 0.0605, 0.1281,
         0.1132]], grad_fn=<SoftmaxBackward0>)

In [16]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[ 0.0268, -0.0150,  0.0122,  ...,  0.0292,  0.0027,  0.0259],
        [-0.0218, -0.0052, -0.0165,  ...,  0.0130,  0.0082,  0.0275]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([ 0.0205, -0.0162], device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0229, -0.0082,  0.0425,  ..., -0.0077, -0.0171, -0.0241],
        [ 0.0274, -0.0409, -0.0437,  ...,  0.0353,  0.0080, -0.0124]],
       device='cuda:0', grad_fn=<Sl

In [17]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

train_dataloader = DataLoader(training_data, batch_size=64)
test_dataloader = DataLoader(test_data, batch_size=64)

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork()

100%|██████████| 26421880/26421880 [00:02<00:00, 12500715.94it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 198097.17it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3703266.54it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 6441610.08it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [18]:
learning_rate = 1e-3
batch_size = 64
epochs = 5

In [19]:
# Initialize the loss function
loss_fn = nn.CrossEntropyLoss()

In [20]:
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [21]:
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    # Set the model to training mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_loop(dataloader, model, loss_fn):
    # Set the model to evaluation mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.eval()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    # Evaluating the model with torch.no_grad() ensures that no gradients are computed during test mode
    # also serves to reduce unnecessary gradient computations and memory usage for tensors with requires_grad=True
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [22]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

epochs = 10
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)
    test_loop(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.310755  [   64/60000]
loss: 2.288719  [ 6464/60000]
loss: 2.270358  [12864/60000]
loss: 2.259776  [19264/60000]
loss: 2.252857  [25664/60000]
loss: 2.211295  [32064/60000]
loss: 2.233783  [38464/60000]
loss: 2.193113  [44864/60000]
loss: 2.191472  [51264/60000]
loss: 2.149935  [57664/60000]
Test Error: 
 Accuracy: 36.6%, Avg loss: 2.147161 

Epoch 2
-------------------------------
loss: 2.170069  [   64/60000]
loss: 2.151537  [ 6464/60000]
loss: 2.093046  [12864/60000]
loss: 2.111058  [19264/60000]
loss: 2.058175  [25664/60000]
loss: 1.986855  [32064/60000]
loss: 2.032108  [38464/60000]
loss: 1.943921  [44864/60000]
loss: 1.954298  [51264/60000]
loss: 1.868786  [57664/60000]
Test Error: 
 Accuracy: 57.3%, Avg loss: 1.873989 

Epoch 3
-------------------------------
loss: 1.913981  [   64/60000]
loss: 1.878175  [ 6464/60000]
loss: 1.762873  [12864/60000]
loss: 1.814001  [19264/60000]
loss: 1.688303  [25664/60000]
loss: 1.634835  [32064/600

In [23]:
torch.save(model, 'model.pth')

In [24]:
model2 = torch.load('model.pth')

In [25]:
model2

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)